from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

import numpy as np

from great_wall_depth.io import write_depth_png, write_json, write_numpy

POSE_PATTERN = re.compile(r"segment_(?P<segment>\d{3})_(?P<pose>A|B|Top)_(?P<sample>\d{4})")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Combine per-sample depth maps generated by the pipeline into a single mosaic"
    )
    parser.add_argument(
        "output_dir",
        type=Path,
        help="Directory that already contains the pipeline outputs (must include summary.json)",
    )
    parser.add_argument(
        "dest",
        type=Path,
        help="Directory where the merged depth maps and metadata should be written",
    )
    parser.add_argument(
        "--poses",
        nargs="*",
        default=("A", "B", "Top"),
        choices=["A", "B", "Top"],
        help="Subset of camera orientations to merge",
    )
    parser.add_argument(
        "--axis",
        choices=["horizontal", "vertical"],
        default="horizontal",
        help="How to arrange the per-sample depth maps inside each mosaic",
    )
    parser.add_argument(
        "--save-npy",
        action="store_true",
        help="Store the merged depth values as .npy files in addition to PNGs",
    )
    return parser.parse_args()


def _load_summary(summary_path: Path) -> Tuple[Dict[str, str], Dict[str, object]]:
    with summary_path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    outputs = data.get("outputs", {})
    config = data.get("config", {})
    return outputs, config


def _group_paths(outputs: Dict[str, str], pose: str) -> List[Tuple[int, int, Path]]:
    grouped: List[Tuple[int, int, Path]] = []
    for key, path_str in outputs.items():
        match = POSE_PATTERN.fullmatch(key)
        if not match:
            continue
        if match.group("pose") != pose:
            continue
        segment = int(match.group("segment"))
        sample = int(match.group("sample"))
        grouped.append((segment, sample, Path(path_str)))
    grouped.sort(key=lambda item: (item[0], item[1]))
    return grouped


def _concatenate_depths(files: Sequence[Path], axis: int) -> np.ndarray:
    depth_maps: List[np.ndarray] = []
    for path in files:
        depth = np.load(path)
        if depth.ndim != 2:
            raise ValueError(f"Depth file {path} is not 2D")
        depth_maps.append(depth)
    if not depth_maps:
        raise RuntimeError("No depth maps found for the requested pose")
    return np.concatenate(depth_maps, axis=axis)


def combine_pose(
    pose: str,
    files: Sequence[Tuple[int, int, Path]],
    axis: str,
    dest_dir: Path,
    far_clip: float,
    save_npy: bool,
) -> None:
    concat_axis = 1 if axis == "horizontal" else 0
    ordered_paths = [path for (_, _, path) in files]
    combined = _concatenate_depths(ordered_paths, axis=concat_axis)

    dest_dir.mkdir(parents=True, exist_ok=True)
    png_path = dest_dir / f"combined_{pose}.png"
    write_depth_png(png_path, combined, far_clip)

    write_json(
        dest_dir / f"combined_{pose}_sources.json",
        [
            {
                "segment_index": segment,
                "sample_index": sample,
                "source": str(path),
            }
            for (segment, sample, path) in files
        ],
    )

    if save_npy:
        write_numpy(dest_dir / f"combined_{pose}.npy", combined)


def main() -> None:
    args = parse_args()
    summary_path = args.output_dir / "summary.json"
    if not summary_path.exists():
        raise FileNotFoundError(f"Could not find summary.json in {args.output_dir}")

    outputs, config = _load_summary(summary_path)
    far_clip = float(config.get("camera", {}).get("far_clip", 200.0))

    for pose in args.poses:
        files = _group_paths(outputs, pose)
        if not files:
            raise RuntimeError(f"No outputs recorded for pose '{pose}'")
        combine_pose(pose, files, args.axis, args.dest, far_clip, args.save_npy)


if __name__ == "__main__":
    main()
